resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/15.yaml

packages:
  - slack-api
  - llamabot-core


extra-deps:
- hflags-0.4.3@sha256:f6b85fc7cbd170787f49225646e62d5589e5dd75abe6f26d16287e5fff3e678e,3121

# flags: {}

# extra-package-dbs: []

# system-ghc: true
#
# require-stack-version: -any # Default
#
# compiler-check: newer-minor
