name: llamabot-core
version: 0.0.1
build-type: Simple
author: dpmesko
maintainer: dpmesko@gmail.com
synopsis: A slackbot that lets you praise others, in Haskell
category: SlackBots

dependencies:
  - base >= 4 && < 5

ghc-options: -Wall -Werror

executables:
  llamabot:
    source-dirs: app/
    main: Main.hs
    other-modules: []
    dependencies: # TODO: come back and remove unnecessary deps here
    - aeson # go?
    - slack-api 
    - stm

    - bytestring
    - case-insensitive
    - containers
    - hflags
    - http-api-data
    - http-client
    - http-client-tls
    - http-types
    - llamabot-core
    - text
    - time
    - transformers
    - wai
    - warp

  llamabot-slash-command:
    source-dirs: app/
    main: SlashCommand.hs
    other-modules: []
    dependencies: # TODO: come back and remove unnecessary deps here
    - aeson # go?

    - bytestring
    - hflags
    - http-client
    - http-client-tls
    - http-types
    - llamabot-core
    - text
    - transformers
    - wai
    - warp
    
    - slack-api # for sure go

library:
  source-dirs: src
  ghc-options: -Wall -O2
  dependencies:
    - aeson
    - bytestring
    - case-insensitive
    - containers
    - hflags
    - http-api-data
    - http-client
    - http-client-tls
    - http-types
    - monad-logger
    - mtl
    - mysql-simple
    - servant-server
    - slack-api
    - stm
    - template-haskell
    - text
    - time
    - transformers
    - wai
    - warp


